#Requires -Modules PnP.PowerShell
<#
.SYNOPSIS
    IMP9177 Seed Missing Lists — sourced from V10.1/V11 MRS
    Populates: MRS_SupplierRegistry, MRS_IngredientRegistry, RAID_Decisions,
               PM_OpenItems, PM_DocumentDeliverables
#>
param([Parameter(Mandatory=$true)][string]$SiteUrl)

Connect-PnPOnline -Url $SiteUrl -ClientId "e7fb3c1d-ac0f-41bc-be47-1356442559eb" -WarningAction SilentlyContinue
Write-Host "✅ Connected" -ForegroundColor Green

# ── MRS_SupplierRegistry — 18 suppliers per V10.1 SUP tab ─────────────────────
Write-Host "`n📋 Seeding MRS_SupplierRegistry (18 suppliers)..." -ForegroundColor Yellow
$suppliers = @(
  @{Title="SUP-001";SUPNumber="SUP-001";VendorID="GYS_2026032707";SupplierName="Honest Science Nutra Co., LTD";SupplierCat="Raw Materials";SupplierPurchaser="Tina Qin";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-002";SUPNumber="SUP-002";VendorID="GYS_2026032706";SupplierName="Yusweet Co., LTD.";SupplierCat="Raw Materials";SupplierPurchaser="Tina Qin";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-003";SUPNumber="SUP-003";VendorID="GYS_2026032705";SupplierName="FocusHerb LLC";SupplierCat="Raw Materials";SupplierPurchaser="Tina Qin";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-004";SUPNumber="SUP-004";VendorID="GYS_2026032704";SupplierName="Ingredion";SupplierCat="Raw Materials";SupplierPurchaser="Tina Qin";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-005";SUPNumber="SUP-005";VendorID="GYS_2026032703";SupplierName="RZBC(JUXIAN) CO., LTD";SupplierCat="Raw Materials";SupplierPurchaser="Tina Qin";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-006";SUPNumber="SUP-006";VendorID="GYS_2026032702";SupplierName="Cargill";SupplierCat="Raw Materials";SupplierPurchaser="Tina Qin";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-007";SUPNumber="SUP-007";VendorID="GYS_2026032701";SupplierName="Amazon";SupplierCat="Laboratory Consumables";SupplierPurchaser="Kevin Xu";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-008";SUPNumber="SUP-008";VendorID="GYS_2025121701";SupplierName="Capol";SupplierCat="Raw Materials";SupplierPurchaser="Kevin Xu";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-009";SUPNumber="SUP-009";VendorID="GYS_2025121601";SupplierName="Hunan Delore Natural Products Co., Ltd";SupplierCat="Raw Materials";SupplierPurchaser="Tina Qin";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-010";SUPNumber="SUP-010";VendorID="V-0000004";SupplierName="Wholesale.BulkSupplements.com";SupplierCat="Raw Materials";SupplierPurchaser="Wenji Wang";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-011";SUPNumber="SUP-011";VendorID="V-0006";SupplierName="Biocatalysts INC";SupplierCat="Raw Materials";SupplierPurchaser="Wenji Wang";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-012";SUPNumber="SUP-012";VendorID="V-0003";SupplierName="Packaging Corporation of America";SupplierCat="Packaging Materials";SupplierPurchaser="Wenji Wang";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-013";SUPNumber="SUP-013";VendorID="V-0005";SupplierName="Pacific Pectin Inc.";SupplierCat="Raw Materials";SupplierPurchaser="Wenji Wang";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-014";SUPNumber="SUP-014";VendorID="V-0002";SupplierName="Jiaherb";SupplierCat="Raw Materials";SupplierPurchaser="Wenji Wang";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-015";SUPNumber="SUP-015";VendorID="V-0001";SupplierName="Jean Niel";SupplierCat="Raw Materials";SupplierPurchaser="Tina Qin";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-016";SUPNumber="SUP-016";VendorID="V-0000012";SupplierName="Hunan Delore Natural Products Co.,Ltd";SupplierCat="Raw Materials";SupplierPurchaser="Wenji Wang";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-017";SUPNumber="SUP-017";VendorID="V-0000011";SupplierName="Restaurant Depot";SupplierCat="Raw Materials";SupplierPurchaser="Wenji Wang";SUPQualStatus="PENDING — Qualification Required"},
  @{Title="SUP-018";SUPNumber="SUP-018";VendorID="V-0000005";SupplierName="ICI Foods";SupplierCat="Raw Materials";SupplierPurchaser="Wenji Wang";SUPQualStatus="PENDING — Qualification Required"}
)
foreach ($s in $suppliers) {
  Add-PnPListItem -List "MRS_SupplierRegistry" -Values $s | Out-Null
  Write-Host "  + $($s.SUPNumber): $($s.SupplierName)" -ForegroundColor Gray
}

# ── MRS_IngredientRegistry — 101 ingredients per V10.1 ING tab ────────────────
Write-Host "`n📋 Seeding MRS_IngredientRegistry (101 ingredients)..." -ForegroundColor Yellow
$ings = @(
  @{INGNumber="ING-001";CPCode="CP_20251216053";INGName="L-Phenylalanine";INGGrade="L-Phenylalanine Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-002";CPCode="CP_20251216085";INGName="L-Theanine";INGGrade="L-theanine";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="FH2025110502";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-003";CPCode="CP_20251216052";INGName="L-Tyrosine";INGGrade="L-Tyrosine Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-004";CPCode="CP_20251216018";INGName="Pectin";INGGrade="Pacific HM100 Gummy Pectin";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="HM100042225-30";INGSupplier="SUP-013";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-005";CPCode="CP_20251216072";INGName="Allulose";INGGrade="Allulose C";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="T125A25L10";INGSupplier="SUP-004";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-006";CPCode="CP_20251216073";INGName="Allulose";INGGrade="Allulose Liquid";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="T251112002";INGSupplier="SUP-004";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-007";CPCode="CP_20251230004";INGName="Glucosamine";INGGrade="GLUCOSAMINE HYDROCHLORIDE";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="HS2510865";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-008";CPCode="CP_20251216059";INGName="Carnauba Wax";INGGrade="Carnauba Wax";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-008";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-009";CPCode="CP_20251216097";INGName="Tomato Extract";INGGrade="White Tomato Extract";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="FH2025112001";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-010";CPCode="CP_20251231001";INGName="Sugar";INGGrade="Granulated Sugar (Domino)";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-006";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-011";CPCode="CP_20251216009";INGName="Sugar";INGGrade="Granulated Sugar (Imperial)";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-006";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-012";CPCode="CP_20251216096";INGName="Kidney Bean Extract";INGGrade="White Kidney Bean P.E.";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="FH2025110901";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-013";CPCode="CP_20251216024";INGName="Food Flavor";INGGrade="83678 - PINEAPPLE O/S";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="US302/25-04";INGSupplier="SUP-015";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-014";CPCode="CP_20251216019";INGName="Food Flavor";INGGrade="83711 - STRAWBERRY O/S";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="US323/25-05";INGSupplier="SUP-015";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-015";CPCode="CP_20251216055";INGName="Choline";INGGrade="Choline L-Bitartrate";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-016";CPCode="CP_20251216044";INGName="Syrup";INGGrade="LorAnn Juicy Lemon Flavor Syrup";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-018";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-017";CPCode="CP_20251216029";INGName="MSM";INGGrade="METHYL-SULFONYL-METHANE";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="HS2510867";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-018";CPCode="CP_20251216057";INGName="Calcium Chloride";INGGrade="Calcium Chloride Dihydrate";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-019";CPCode="CP_20260106008";INGName="Anti Stick Oil";INGGrade="Anti Stick Oil CAP45-4915/10";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-020";CPCode="CP_20251216078";INGName="Coenzyme Q10";INGGrade="Coenzyme Q10 (Ubiquinone)";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="FH2025110702";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-021";CPCode="CP_20251216031";INGName="Magnesium Glycinate";INGGrade="Magnesium Glycinate";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-022";CPCode="CP_20251216083";INGName="Glutathione";INGGrade="Glutathione";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="FH2025110302";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-023";CPCode="CP_20251216068";INGName="Guarana Extract";INGGrade="Guarana Extract Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-024";CPCode="CP_20251231002";INGName="Pectin";INGGrade="Pectin(Dutch-Jell)";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-013";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-025";CPCode="CP_20251216036";INGName="Pectin";INGGrade="Pectin(Pectner)";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-013";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-026";CPCode="CP_20251216021";INGName="Food Flavor";INGGrade="83271 - RED FRUIT";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="US301/25-01";INGSupplier="SUP-015";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-027";CPCode="CP_20251216014";INGName="Food Color";INGGrade="Red Food Color";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-028";CPCode="CP_20251216089";INGName="Resveratrol";INGGrade="Polygonum cuspidatum Extract";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="FH2025103001";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-029";CPCode="CP_20251216043";INGName="Syrup";INGGrade="LorAnn Banana Royale Flavor Syrup";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-018";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-030";CPCode="CP_20251216065";INGName="Vitamin K2";INGGrade="Vitamin K2 MK-7 Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="FH2025110402";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-031";CPCode="CP_20251216081";INGName="Elderberry Extract";INGGrade="Elderberry Extract";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-032";CPCode="CP_20251216061";INGName="Caffeine";INGGrade="Caffeine Powder Anhydrous Pure";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="FH2025111903";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-033";CPCode="CP_20260106011";INGName="Moringa Extract";INGGrade="Moringa Extract Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="US301/25-05";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-034";CPCode="CP_20251230003";INGName="Blue Berry Extract";INGGrade="Blue Berry Extract";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-035";CPCode="CP_20251216027";INGName="Food Flavor";INGGrade="83559 - BLUEBERRY O/S";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-015";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-036";CPCode="CP_20251216025";INGName="Food Flavor";INGGrade="83628 - BLUE RASPBERRY O/S";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-015";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-037";CPCode="CP_20260211006";INGName="Water";INGGrade="Deionized Water";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-038";CPCode="CP_20260211007";INGName="Food Flavor";INGGrade="Lychee Flavor";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-015";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-039";CPCode="CP_20251216030";INGName="Glucosamine";INGGrade="Glucosamine Sulfate";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="HS2510464";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-040";CPCode="CP_20251216077";INGName="Chondroitin";INGGrade="CHONDROITIN SULFATE SODIUM";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-041";CPCode="CP_20251216013";INGName="Food Color";INGGrade="Green Food Color";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-042";CPCode="CP_20251216060";INGName="Calcium Chloride";INGGrade="Calcium Chloride Powder";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="C125A25L02";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-043";CPCode="CP_20260106010";INGName="Syrup";INGGrade="Monk Fruit Extract Syrup";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="C251105004";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-044";CPCode="CP_20251216071";INGName="Monk Fruit Extract";INGGrade="Monk Fruit Extract Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-045";CPCode="CP_20251216034";INGName="Food Color";INGGrade="Radish Red Color";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="US302/25-05";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-046";CPCode="CP_20251216008";INGName="Food Color";INGGrade="E18 Pyocyanin Blue";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-047";CPCode="CP_20251216086";INGName="Maltitol";INGGrade="Maltitol C";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-048";CPCode="CP_20251216026";INGName="Maltitol";INGGrade="Liquid Maltitol";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-049";CPCode="CP_20260325001";INGName="Maltose";INGGrade="Maltose Powder";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-050";CPCode="CP_20251216023";INGName="Food Flavor";INGGrade="83326 - MANGO O/S";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-015";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-051";CPCode="CP_20251216041";INGName="Syrup";INGGrade="LorAnn Mango Flavor Syrup";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="US302/25-05";INGSupplier="SUP-018";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-052";CPCode="CP_20260302001";INGName="Food Color";INGGrade="Yellow Food Color";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-053";CPCode="CP_20251216038";INGName="Gelatin";INGGrade="Gelatin";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-054";CPCode="CP_20251216022";INGName="Food Flavor";INGGrade="83359 - LEMON";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-015";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-055";CPCode="CP_20251216012";INGName="Citric Acid";INGGrade="Citric Acid Anhydrous 30-100MESH(RZBC)";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="0052978604";INGSupplier="SUP-005";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-056";CPCode="CP_20251230002";INGName="Calcium Citrate";INGGrade="Calcium Citrate";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="FH2025111901";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-057";CPCode="CP_20251216067";INGName="Potassium Citrate";INGGrade="Potassium Citrate Powder";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="HS2510866";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-058";CPCode="CP_20251216020";INGName="Magnesium Citrate";INGGrade="Magnesium Citrate";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-059";CPCode="CP_20251216017";INGName="Sodium Citrate";INGGrade="Sodium-Citrate";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-060";CPCode="CP_20251216051";INGName="Taurine";INGGrade="Taurine";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="US337/25-04";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-061";CPCode="CP_20251216079";INGName="Collagen";INGGrade="COLLAGEN";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="FH2025111802";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-062";CPCode="CP_20251216035";INGName="Food Flavor";INGGrade="Apple Flavor";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="FH2025111902";INGSupplier="SUP-015";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-063";CPCode="CP_20251230001";INGName="Malic Acid";INGGrade="Malic Acid";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-064";CPCode="CP_20251216011";INGName="Food Flavor";INGGrade="83563 - GRAPE O/S";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-015";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-065";CPCode="CP_20251216047";INGName="Zinc Gluconate";INGGrade="Zinc Gluconate";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="US337/25-04";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-066";CPCode="CP_20251216084";INGName="Grape Seed Extract";INGGrade="Grape seed extract";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="FH2025111802";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-067";CPCode="CP_20251216040";INGName="Syrup";INGGrade="LorAnn Georgia Peach Flavor Syrup";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="FH2025111902";INGSupplier="SUP-018";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-068";CPCode="CP_20251216063";INGName="Vitamin B12";INGGrade="Vitamin B12 Powder (Cyanocobalamin)";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-069";CPCode="CP_20260121001";INGName="Agar Agar";INGGrade="Agar Agar";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-070";CPCode="CP_20260327001";INGName="Calcium Lactate";INGGrade="Calcium Lactate";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="FH2025110801";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-071";CPCode="CP_20251216062";INGName="Calcium Lactate";INGGrade="Calcium Lactate Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-072";CPCode="CP_20251216037";INGName="Sorbitol";INGGrade="Sorbitol Powder (70%)";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-073";CPCode="CP_20251216069";INGName="Lactic Acid";INGGrade="Vegan Lactic Acid Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-074";CPCode="CP_20251216048";INGName="Calcium Carbonate";INGGrade="Calcium Carbonate";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-075";CPCode="CP_20251216016";INGName="Food Color";INGGrade="Natural Blue Color";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-076";CPCode="CP_20251216070";INGName="Stevia Extract";INGGrade="Stevia Extract Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-077";CPCode="CP_20251216090";INGName="Sodium Hyaluronate";INGGrade="sodium hyaluronate";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-078";CPCode="CP_20251216028";INGName="Melatonin";INGGrade="Melatonin";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CRITICAL — ISS-010";INGLotNum="FH2025110701";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-079";CPCode="CP_20251216046";INGName="Mould Release Oil";INGGrade="Mould Release Oil";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="US301/25-04";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-080";CPCode="CP_20251216087";INGName="Marigold Extract";INGGrade="Lutein Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="40900097.0";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-081";CPCode="CP_20251216088";INGName="Marigold Extract";INGGrade="Zeaxanthin Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-082";CPCode="CP_20251216091";INGName="Vitamin A";INGGrade="Vitamin A Palmitate Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-083";CPCode="CP_20251216092";INGName="Vitamin B3";INGGrade="Vitamin B3(Nicotinamide)";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-084";CPCode="CP_20251216093";INGName="Vitamin B6";INGGrade="Vitamin B6 (Pyridoxine HCL)";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-085";CPCode="CP_20251216075";INGName="Biotin";INGGrade="Biotin";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-086";CPCode="CP_20251216032";INGName="Vitamin C";INGGrade="Vitamin C";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="FH2025111901";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-087";CPCode="CP_20251216094";INGName="Vitamin D3";INGGrade="Vitamin D3";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="HS2510866";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-088";CPCode="CP_20251216095";INGName="Vitamin E";INGGrade="Vitamin E";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-089";CPCode="CP_20251216039";INGName="Food Flavor";INGGrade="Strawberry Food Flavor(Oringer)";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-015";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-090";CPCode="CP_20251216074";INGName="Astaxanthin";INGGrade="Astaxanthin Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-091";CPCode="CP_20251216042";INGName="Syrup";INGGrade="Hawaiian Pineapple Flavor Syrup";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-018";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-092";CPCode="CP_20251216058";INGName="Vitamin B3";INGGrade="Niacin Powder (VB3)";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="FH2025110101";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-093";CPCode="CP_20251216049";INGName="L-Lysine";INGGrade="L-Lysine Mono HCL";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-094";CPCode="CP_20251216056";INGName="Berberine HCl";INGGrade="Berberine HCl Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA on File";INGLotNum="FH2025110401";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-095";CPCode="CP_20251216080";INGName="Creatine";INGGrade="Creatine Monohydrate";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-096";CPCode="CP_20260211008";INGName="Creatine";INGGrade="Creatine Monohydrate Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-097";CPCode="CP_20251216050";INGName="Apple Cider Vinegar";INGGrade="Organic Apple Cider Vinegar Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-098";CPCode="CP_20251216033";INGName="DHA";INGGrade="DHA Powder";INGCategory="Dietary Ingredient";INGDietary="YES — 100% per-lot ID test req.";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-099";CPCode="CP_20251216010";INGName="Corn Syrup";INGGrade="011440-000 CASCO 42 DE Corn Syrup";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA on File";INGLotNum="3104187317.0";INGSupplier="SUP-006";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-100";CPCode="CP_20251216007";INGName="Food Color";INGGrade="E18 Pyocyanin Blue";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"},
  @{INGNumber="ING-101";CPCode="CP_20251216015";INGName="Food Color";INGGrade="Purple Food Color";INGCategory="Excipient/Flavoring/Other";INGDietary="No";INGCoAStatus="CoA Missing — Action Required";INGLotNum="(none on file)";INGSupplier="SUP-001";INGSpecStatus="PENDING — Specification Required"}
)
$count = 0
foreach ($ing in $ings) {
  $ing["Title"] = $ing["INGNumber"]
  Add-PnPListItem -List "MRS_IngredientRegistry" -Values $ing | Out-Null
  $count++
  if ($count % 10 -eq 0) { Write-Host "  ... $count ingredients seeded" -ForegroundColor Gray }
}
Write-Host "  ✅ $count ingredients seeded" -ForegroundColor Green

# ── RAID_Decisions — 11 key decisions from V11 ────────────────────────────────
Write-Host "`n📋 Seeding RAID_Decisions (11 decisions)..." -ForegroundColor Yellow
$decisions = @(
  @{Title="DEC-001";DecisionID="DEC-001";DecisionMtg="MM-001";DecisionMade="Project scope confirmed: 21 CFR Part 111 + FSMA dual compliance. Phase 1 gap assessment first.";DecisionBy="Andre Butler + Liu Hong";DecisionImpact="High"},
  @{Title="DEC-005";DecisionID="DEC-005";DecisionMtg="MM-002";DecisionMade="77 total gaps identified. 67 compliance gaps + 10 GAP-REC record creation gaps owned entirely by 3H with zero ADB cost impact.";DecisionBy="Andre Butler";DecisionImpact="High"},
  @{Title="DEC-010";DecisionID="DEC-010";DecisionMtg="MM-003";DecisionMade="Phase 2 QMS implementation to proceed. Document delivery in weekly batches (W1, W2, etc.) with one CR and one DCO per weekly set.";DecisionBy="Andre Butler + Tina Qin";DecisionImpact="High"},
  @{Title="DEC-018";DecisionID="DEC-018";DecisionMtg="MM-003";DecisionMade="One CR and one DCO per weekly deliverable set regardless of how many batches ship that week. Sequential numbering: CR/DCO-0001 = W1, etc.";DecisionBy="Andre Butler";DecisionImpact="Medium"},
  @{Title="DEC-035";DecisionID="DEC-035";DecisionMtg="MM-005";DecisionMade="Amazon-sourced ingredients excluded from quality/ASL scope — R&D use only. 18 production vendors confirmed in Approved Supplier List.";DecisionBy="Andre Butler + Tina Qin";DecisionImpact="High"},
  @{Title="DEC-036";DecisionID="DEC-036";DecisionMtg="MM-005";DecisionMade="Customer-supplied RM: Option 2 (Path B) — CoA + contractual supplier responsibility transfer. ADB to draft clause language.";DecisionBy="Andre Butler + Tina Qin";DecisionImpact="High"},
  @{Title="DEC-037";DecisionID="DEC-037";DecisionMtg="MM-005";DecisionMade="Caffeine with no CoA cannot be used in production. Disposal recommended per §111.80. ING-032 flagged.";DecisionBy="Andre Butler";DecisionImpact="Critical — Blocking"},
  @{Title="DEC-038";DecisionID="DEC-038";DecisionMtg="MM-005";DecisionMade="FOB Origin confirmed. 3H liability ends at 3H dock. EXW language to be added to all supplier invoices going forward.";DecisionBy="Andre Butler + Tina Qin";DecisionImpact="Medium"},
  @{Title="DEC-039";DecisionID="DEC-039";DecisionMtg="MM-005";DecisionMade="R&D sample batch exemption from quality documentation established. Separate R&D log to be maintained by QD Yang.";DecisionBy="Andre Butler + Tina Qin";DecisionImpact="Medium"},
  @{Title="DEC-040";DecisionID="DEC-040";DecisionMtg="MM-005";DecisionMade="Tina Qin confirmed as interim QA Approver for ALL controlled document sign-offs. QD Yang = operational QA duties only — not a document signer. ADB to research QD Yang work authorization status (AC-034).";DecisionBy="Andre Butler + Tina Qin + Liu Hong";DecisionImpact="Critical — Blocking"},
  @{Title="DEC-041";DecisionID="DEC-041";DecisionMtg="MM-005";DecisionMade="Apr 8/9/10 delivery schedule confirmed. W2 feedback target Apr 14. Next formal meeting week of Apr 21 (Tina travel Apr 13-17). No meetings during travel.";DecisionBy="Andre Butler + Tina Qin";DecisionImpact="High"}
)
foreach ($d in $decisions) {
  Add-PnPListItem -List "RAID_Decisions" -Values $d | Out-Null
  Write-Host "  + $($d.DecisionID)" -ForegroundColor Gray
}

# ── PM_OpenItems — 8 critical open items ─────────────────────────────────────
Write-Host "`n📋 Seeding PM_OpenItems (8 items)..." -ForegroundColor Yellow
$openItems = @(
  @{Title="ISS-010: Melatonin CoA";OIRef="ISS-010";OITitle="Melatonin Powder (ING-078) — No CoA on file. Active production ingredient. §111.75(a)(1) violation. CRITICAL.";OIOwner="3H — Tina Qin";OIPriority="Critical";OIStatus="Open — Critical"},
  @{Title="DCO-0001 Sign-Off PAST DUE";OIRef="DCO-0001";OITitle="W1 Sign-off PAST DUE — was Apr 10. Tina Qin + Liu Hong must sign. QD Yang blocker (AC-034) unresolved. 15 documents affected.";OIOwner="3H — Tina Qin";OIPriority="Critical";OIStatus="At Risk — Past Due"},
  @{Title="AC-034: QD Yang Research";OIRef="AC-034";OITitle="ADB to research QD Yang work authorization status. BLOCKING DCO-0001 execution. Decision DEC-040 confirmed Tina Qin as interim QA Approver.";OIOwner="ADB (Andre)";OIPriority="Critical";OIStatus="Open — Action Required"},
  @{Title="AC-023: Orkin Pest Addendum";OIRef="AC-023";OITitle="Orkin stored product pest addendum URGENT. Contact Autumn Bailey before facility inspection. Required for pest control SOP compliance.";OIOwner="3H — Tina Qin";OIPriority="Critical";OIStatus="Open — Urgent"},
  @{Title="W2 Feedback Due Apr 14";OIRef="W2-FB";OITitle="W2 15-document package delivered to 3H Apr 10. Feedback due Apr 14–17 (Tina travel). Sign-off target Apr 17 or Apr 20 post-feedback.";OIOwner="3H — Tina Qin";OIPriority="High";OIStatus="In Progress"},
  @{Title="AC-006: Warehouse Inventory";OIRef="AC-006";OITitle="Warehouse inventory list OVERDUE since Mar 26. Blocking HARPC PLN-FS-001 completion. KJ/Cindy to provide complete inventory.";OIOwner="3H — Cindy Dong";OIPriority="Critical";OIStatus="Past Due"},
  @{Title="AC-012: Structural Exclusion";OIRef="AC-012";OITitle="Structural exclusion assessment overdue. Required for HARPC environmental monitoring and pest exclusion sections (SOP-FS-004).";OIOwner="3H — Tina Qin";OIPriority="High";OIStatus="Past Due"},
  @{Title="PSO-CO-001: Change Order";OIRef="PSO-CO-001";OITitle="Phase 2 Change Order pending execution. Blocks Phase 2B authorization and expanded scope engagement beyond current PSO ceiling.";OIOwner="3H — Tina Qin";OIPriority="High";OIStatus="Pending 3H Action"}
)
foreach ($i in $openItems) {
  Add-PnPListItem -List "PM_OpenItems" -Values $i | Out-Null
  Write-Host "  + $($i.OIRef)" -ForegroundColor Gray
}

# ── PM_DocumentDeliverables — 25 docs W1 + W2 per V11 CR-DCO tab ──────────────
Write-Host "`n📋 Seeding PM_DocumentDeliverables (25 docs)..." -ForegroundColor Yellow
$deliverables = @(
  # W1 — 15 documents — DCO-0001 PAST DUE
  @{Title="1.1-QM-001";PMDocID="1.1";PMDocNumber="QM-001";PMDocWeek="W1";PMDocTitle="Quality Manual";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  @{Title="1.2-SOP-QMS-001";PMDocID="1.2";PMDocNumber="SOP-QMS-001";PMDocWeek="W1";PMDocTitle="Management Responsibility & QU Designation SOP";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  @{Title="1.3-SOP-QMS-002";PMDocID="1.3";PMDocNumber="SOP-QMS-002";PMDocWeek="W1";PMDocTitle="Document Control SOP";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  @{Title="1.4-SOP-QMS-003";PMDocID="1.4";PMDocNumber="SOP-QMS-003";PMDocWeek="W1";PMDocTitle="Change Control SOP";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  @{Title="1.5-FM-001";PMDocID="1.5";PMDocNumber="FM-001";PMDocWeek="W1";PMDocTitle="Master Document Log";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  @{Title="1.6-FM-002";PMDocID="1.6";PMDocNumber="FM-002";PMDocWeek="W1";PMDocTitle="Change Request Form";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  @{Title="1.7-FM-003";PMDocID="1.7";PMDocNumber="FM-003";PMDocWeek="W1";PMDocTitle="Document Change Order Form";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  @{Title="1.8-FM-027";PMDocID="1.8";PMDocNumber="FM-027";PMDocWeek="W1";PMDocTitle="QU & Qualified Supervisor Designation Form";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  @{Title="1.9-FM-030";PMDocID="1.9";PMDocNumber="FM-030";PMDocWeek="W1";PMDocTitle="Finished Product Specification Sheet Template";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  @{Title="1.10-FPS-001";PMDocID="1.10";PMDocNumber="FPS-001";PMDocWeek="W1";PMDocTitle="Finished Product Specification — Lychee VD3 Gummy";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  @{Title="E-1-SOP-PRD-108";PMDocID="E-1";PMDocNumber="SOP-PRD-108";PMDocWeek="W0";PMDocTitle="Finished Product Release Management (Existing)";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  @{Title="E-2-SOP-RCL-321";PMDocID="E-2";PMDocNumber="SOP-RCL-321";PMDocWeek="W0";PMDocTitle="Product Recall Procedure (Existing)";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  @{Title="E-3-SOP-PRD-432";PMDocID="E-3";PMDocNumber="SOP-PRD-432";PMDocWeek="W0";PMDocTitle="Finished Product Specifications & Testing (Existing)";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  @{Title="E-4-SOP-FRS-549";PMDocID="E-4";PMDocNumber="SOP-FRS-549";PMDocWeek="W0";PMDocTitle="Product Specification Sheet SOP (Existing)";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  @{Title="E-5-FM-025";PMDocID="E-5";PMDocNumber="FM-025";PMDocWeek="W0";PMDocTitle="Finished Product Release Review Record (Existing)";PMDocStatus="PAST DUE — Sign-Off Overdue"},
  # W2 — 13 documents — Pending Feedback
  @{Title="2.1-SOP-SUP-001";PMDocID="2.1";PMDocNumber="SOP-SUP-001";PMDocWeek="W2";PMDocTitle="Supplier Qualification SOP";PMDocStatus="Delivered — Pending Feedback"},
  @{Title="2.2-SOP-SUP-002";PMDocID="2.2";PMDocNumber="SOP-SUP-002";PMDocWeek="W2";PMDocTitle="Incoming Material Receiving & Inspection SOP";PMDocStatus="Delivered — Pending Feedback"},
  @{Title="2.3-SOP-FS-001";PMDocID="2.3";PMDocNumber="SOP-FS-001";PMDocWeek="W2";PMDocTitle="Allergen Control SOP";PMDocStatus="Delivered — Pending Feedback"},
  @{Title="2.4-SOP-FS-002";PMDocID="2.4";PMDocNumber="SOP-FS-002";PMDocWeek="W2";PMDocTitle="Equipment Cleaning & Disinfection SOP";PMDocStatus="Delivered — Pending Feedback"},
  @{Title="2.5-SOP-FS-003";PMDocID="2.5";PMDocNumber="SOP-FS-003";PMDocWeek="W2";PMDocTitle="Facility Sanitation SOP";PMDocStatus="Delivered — Pending Feedback"},
  @{Title="2.6-SOP-FS-004";PMDocID="2.6";PMDocNumber="SOP-FS-004";PMDocWeek="W2";PMDocTitle="Environmental Monitoring SOP";PMDocStatus="Delivered — Pending Feedback"},
  @{Title="2.7-SOP-PC-001";PMDocID="2.7";PMDocNumber="SOP-PC-001";PMDocWeek="W2";PMDocTitle="Pest Sighting Response SOP";PMDocStatus="Delivered — Pending Feedback"},
  @{Title="2.8-FM-004";PMDocID="2.8";PMDocNumber="FM-004";PMDocWeek="W2";PMDocTitle="Approved Supplier List Template";PMDocStatus="Delivered — Pending Feedback"},
  @{Title="2.9-FM-005";PMDocID="2.9";PMDocNumber="FM-005";PMDocWeek="W2";PMDocTitle="Receiving Log / Incoming Inspection Record Template";PMDocStatus="Delivered — Pending Feedback"},
  @{Title="2.10-FM-006";PMDocID="2.10";PMDocNumber="FM-006";PMDocWeek="W2";PMDocTitle="Raw Material Specification Sheet Template";PMDocStatus="Delivered — Pending Feedback"},
  @{Title="2.11-FM-007";PMDocID="2.11";PMDocNumber="FM-007";PMDocWeek="W2";PMDocTitle="Material Quarantine / Hold Label Template";PMDocStatus="Delivered — Pending Feedback"},
  @{Title="2.12-FM-ALG";PMDocID="2.12";PMDocNumber="FM-ALG";PMDocWeek="W2";PMDocTitle="Allergen Status Record Template";PMDocStatus="Delivered — Pending Feedback"},
  @{Title="2.13-FM-008";PMDocID="2.13";PMDocNumber="FM-008";PMDocWeek="W2";PMDocTitle="Supplier CoA Requirements Checklist";PMDocStatus="Delivered — Pending Feedback"}
)
foreach ($d in $deliverables) {
  Add-PnPListItem -List "PM_DocumentDeliverables" -Values $d | Out-Null
  Write-Host "  + $($d.PMDocNumber)" -ForegroundColor Gray
}

Write-Host "`n🎉 All missing lists seeded from V10.1/V11!" -ForegroundColor Green
Write-Host "  MRS_SupplierRegistry:    18 suppliers (actual V10.1 names + vendor IDs)" -ForegroundColor White
Write-Host "  MRS_IngredientRegistry:  101 ingredients (full ING-001 through ING-101)" -ForegroundColor White
Write-Host "  RAID_Decisions:          11 decisions (DEC-001 through DEC-041 key)" -ForegroundColor White
Write-Host "  PM_OpenItems:            8 critical open items" -ForegroundColor White
Write-Host "  PM_DocumentDeliverables: 28 docs (W0 existing + W1 + W2 per V11)" -ForegroundColor White
Disconnect-PnPOnline
